### ISSUE TITLE
Method "GetMessagesForConversation" function for parameter "messageCount" unclear

### ISSUE THREAD

**Issue by morbiida0** [henrydatei/knuddels-api#2]
I am trying to use the API. The method "GetMessagesForConversation" has the parameter "messageCount". What exactly is the parameter doing? No matter what value I use for the parameter, the outcome is always the same. As there is no documentation for the API, could you please clarify what the parameter is doing?

Thanks a lot

**Comment by Bizarrus** [comment]
`messageCount` is the number of messages loaded in the conversation.

A conversation can have X number of messages. Usually the last 10 messages are loaded. If you want to load older messages (see app behavior), you must change the parameters here.

**Tip:**
Look for `graphql` requests via app.knuddels.de in the browser's network monitor.
